baseurl = "/"
languageCode = "en-us"
title = "Blog Title"
author = "Authors Name"
pygmentsCodeFences = true
paginate = 5

[outputs]
  home = ["HTML", "RSS", "JSON"]

[params]
  hero = "Base16"
  message = "Sub Title message"
  descriptions = "Blog description"
  twitter = "twitter user"
