baseURL = "https://admin.redbrick.dcu.ie/"
languageCode = "en-us"
title = "Redbrick Admin Blog"
author = "Redbrick Admin"
pygmentsCodeFences = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

[params]
  hero = "root@redbrick"
  message = "FIX IT!!! FIX IT !!! FIX ITTTTTT!!!!!!!!!"
