baseURL = "https://admins.redbrick.dcu.ie/"
languageCode = "en-us"
title = "Redbrick Admin Blog"
author = "Redbrick Admin"
pygmentsCodeFences = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

[params]
  hero = "root@rb"
  message = "FIX IT!!! FIX IT !!! FIX ITTTTTT!!!!!!!!!"
  descriptions = "Tales of fail from Redbrick admins"
  twitter = "RedbrickDCU"
